version: '3.8'

services:
  db:
    image: postgres:15
    container_name: file_storage_organizer_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: file_storage
    ports:
      - "5654:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_storage_organizer_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:123321@db:5432/file_storage
      - SECRET_KEY=75_57_75
      - WTF_CSRF_ENABLED=True
    env_file:
      - .env

volumes:
  pgdata:
